project:
  type: website
  render:
    - "*.qmd"
    - "2026-guz/**/*.qmd"
    - "!2026-guz/08_glm-gam-and-more/ceviri/ahmetbatuhankaya-20269348005.qmd"

website:
  title: "XAI Dersi"
  navbar:
    left:
      - href: index.qmd
        text: Ana Sayfa

format:
  html:
    theme: cosmo
    toc: true
